#!/usr/bin/env python3

"""
Analyse malicious files using online apis

Usage: remote-anal [-h|-v] [-k KEY] URI...

Options:
    -h, --help          Print this help and exit
    -v, --version       Print version and exit
    -k, --apikey KEY    Use KEY to authenticate to the VirusTotal api.
                        If KEY is a path to a file, reads the key from there.
                        Default is ~/.vtsend.key

Arguments:
    URI     URI can be 3 things:
            - an url (identified by the presence of ://) pointing to
              a potentially malicious file
            - a path to a suspicious file
              (if bigger than 32MB, falls back to MD5)
            - a MD5 checksum of a suspicious file
              No key is required for MD5 checksums as VirusTotal isn't used
"""

import re
import os
import sys
import json
import time
import hashlib
import requests
from path       import Path
from docopt     import docopt
from subprocess import getoutput


def api_key(key, *, key_reg=re.compile("[0-9a-f]{64}")):
    """
    Recover the API key from either command line arguments or a file
    """
    default_path = "~/.virustotal.apikey"

    if key is None:
        key = default_path

    if key is not None:
        if key_reg.fullmatch(key) is not None:
            return key

    path = Path(key).expanduser()
    if not os.path.exists(path):
        path = Path(default_path).expanduser()

    try:
        return open(path).read(64)
    except FileNotFoundError:
        return None


def post_request(command, resource, key):
    """
    Dispatch a request to its handler.
    `command' must be one of:
        - send_md5
        - send_file
        - send_url
        - md5_report
        - file_report
        - url_report
    """
    # If MD5, use team-cymru's API
    if command == "send_md5":
        return tc_request(resource)

    if command == "md5_report":
        return resource

    # We're using VirusTotal
    if command == "send_file":
        return vt_send(resource, key)

    if command == "scan_url":
        return vt_scan(resource, key)

    if "report" in command:
        return vt_report(command, resource, key)


def vt_send(filename, key):
    """
    Send a file to VirusTotal
    """
    url   = "https://www.virustotal.com/vtapi/v2/file/scan"
    attr  = {"apikey": key}
    files = {"file": open(filename, 'rb')}
    res   = requests.post(url, data=attr, files=files)

    if res.status_code == 200:
        return res.text
    else:
        return res.text


def vt_scan(resource, key):
    """
    Send a url to VirusTotal
    """
    url  = "https://www.virustotal.com/vtapi/v2/url/scan"
    attr = {"apikey": key, "url":resource}
    res  = requests.post(url, data=attr)

    if res.status_code == 200:
        return res.text
    else:
        return res.text


def vt_report(command, resource, key):
    """
    Get a report from VirusTotal
    """
    if command == "file_report":
        url = "https://www.virustotal.com/vtapi/v2/file/report"
        res = json.loads(resource)["sha256"]

    elif command == "url_report":
        url = "https://www.virustotal.com/vtapi/v2/url/report"
        res = resource

    else:
        return None

    response = retrieve_report(res, url, key)
    return json.loads(response.text)



def retrieve_report(resource, url, key):
    """
    Retrieve report for the given file
    """
    # TODO: manage time
    params = {"apikey": key, "resource": resource}
    res = requests.post(url, data=params)

    while res.status_code == 204 or json.loads(res.text)["response_code"] == -2:
        time.sleep(15)
        res = requests.post(url, data=params)

    return res


def tc_request(resource, *, md5_reg=re.compile("[0-9a-f]{32}")):
    """
    Send a MD5 to Team-Cymru
    """
    resource = resource.lower()

    if md5_reg.fullmatch(resource) is None:
        sys.exit("Incorrect hash" + resource)

    return tc_parse(getoutput("whois -h hash.cymru.com " + resource))


def tc_parse(data):
    """
    Parse a Team-Cymru report
    """
    digest, time, status = data.split()
    result = {"md5": digest, "timestamp": time}

    if status == "NO_DATA":
        result["status"] = "UKNOWN"
    else:
        result = status_from_percentage(int(status))

    return result


def status_from_percentage(positive, total=100):
    """
    Get a named status from a percentage, useful for logging
    """
    ratio = positive * 100 // total

    states = [(  0, "CLEAN" ),
              ( 40, "LOW"   ),
              ( 80, "MEDIUM"),
              ( 99, "HIGH"  ),
              (100, "ALERT" )]

    for rate, state in states:
        if ratio <= rate:
            return state


def file_digest(path, algo=hashlib.md5):
    """
    Efficiently get a digest for a file, default algorithm is MD5
    """
    checksum = algo()
    with open(path, 'rb') as f:
        for chunk in iter(lambda: f.read(4096), b""):
            checksum.update(chunk)
    return checksum.hexdigest()


def daemonize(*, UMASK=0, WORKDIR="/", MAXFD=1024):
   """
   Detach a process from the controlling terminal and run it in the
   background as a daemon.
   """
   if  hasattr(os, "devnull"):
      REDIRECT_TO = os.devnull
   else:
      REDIRECT_TO = "/dev/null"

   try:
      pid = os.fork()
   except OSError as e:
      raise Exception("%s [%d]" % (e.strerror, e.errno))

   if pid == 0:
      os.setsid()

      try:
         pid = os.fork()
      except OSError as e:
         raise Exception("%s [%d]" % (e.strerror, e.errno))

      if pid == 0:
         os.chdir(WORKDIR)
         os.umask(UMASK)
      else:
         os._exit(0)
   else:
      os._exit(0)

   import resource
   maxfd = resource.getrlimit(resource.RLIMIT_NOFILE)[1]
   if maxfd == resource.RLIM_INFINITY:
      maxfd = MAXFD

   for fd in range(0, maxfd):
      try:
         os.close(fd)
      except OSError:
         pass

   os.open(REDIRECT_TO, os.O_RDWR)

   os.dup2(0, 1)
   os.dup2(0, 2)

   return 0


def main():
    args = docopt(__doc__, version="vtsend 0.9 - VirusTotal API v2.0")
    key  = api_key(args["--apikey"])
    uris = args["URI"]

    need_daemon = False
    responses   = []
    for uri in uris:
        if "://" in uri:
            if key is None:
                sys.exit("Unable to open file: " + args["--apikey"])
            resp = ("url_report",
                    post_request("scan_url", uri, key))
            need_daemon = True

        elif re.fullmatch("([a-f0-9]|[A-F0-9]){32}", uri):
            resp = ('md5_report',
                    post_request("send_md5", uri.lower(), key))

        else:
            path = Path(uri).expanduser()

            # VirusTotal doesn't accept files bigger than 32MB
            if os.stat(path).st_size < 33554432:
                if key is None:
                    sys.exit("Unable to open file: " + args["--apikey"])
                resp = ('file_report', post_request("send_file", uri, key))
                need_daemon = True
            else:
                resp = ('md5_report',
                        post_request("send_md5", file_digest(path), key))

        print("REQUEST\n" + str(resp))
        responses.append(resp)

    need_daemon = False # For debug, don't daemonize
    if need_daemon:
        daemonize()

    for resp in responses:
        print("RESPONSE\n" + str(post_request(*resp, key)))


if __name__ == "__main__":
    main()
